name: tests
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.5'
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.483'
      - name: Run tests
        run: bin/test